# מקמפל את ה-stub שיושב בשורש הכונן. דורש Visual Studio עם כלי C++
# (קיים על windows-latest ב-GitHub Actions). להרצה עם pwsh 7 — הקבצים כאן
# הם UTF-8 בלי BOM, ו-Windows PowerShell 5.1 יקרא אותם בקוד־עמוד המערכת.
$ErrorActionPreference = 'Stop'

$sourceDir = $PSScriptRoot
$outDir = Join-Path $sourceDir 'build'
New-Item -ItemType Directory -Force $outDir | Out-Null

# stub.rc מטמיע את המכל הזה, ולכן הוא חייב להיות קיים לפני rc.exe.
$payloadFile = Join-Path $outDir 'payload.otz'
if (-not (Test-Path $payloadFile)) {
  throw "payload.otz not found at $payloadFile — run windows_stub\package.ps1 instead; it builds the payload and then calls this script."
}

# גרסת ה-payload באה ממקום אחד — pubspec.yaml — ומגיעה גם ל-stub.c (המרקר
# `.ready`, שהוא מה שמכריע אם צריך לחלץ מחדש אחרי עדכון עצמי) וגם למשאב
# הגרסה של ה-exe. חייבת להיות זהה ל-`appVersion` שב-lib/src/app_version.dart.
$pubspec = Join-Path (Split-Path -Parent $sourceDir) 'pubspec.yaml'
$versionLine = Select-String -Path $pubspec -Pattern '^version:\s*(.+)$' | Select-Object -First 1
if (-not $versionLine) { throw "No 'version:' line found in $pubspec." }
$version = $versionLine.Matches[0].Groups[1].Value.Trim().Split('+')[0]
if ($version -notmatch '^\d+(\.\d+)*$') {
  throw "Unexpected version '$version' in $pubspec — expected digits and dots."
}
# FILEVERSION דורש ארבעה מספרים מופרדים בפסיקים.
$parts = @($version.Split('.')) + @('0', '0', '0', '0')
$commas = ($parts[0..3]) -join ','
# אנגלית ו-ASCII בלבד: את הקובץ הזה קורא גם rc.exe, וקידוד של קובץ שמוכלל
# ב-.rc הוא בדיוק סוג התקלה שאין טעם להיכנס אליה בקובץ מיוצר.
# _W היא אותה גרסה בדיוק — היא נמסרת ללאנצ'ר במשתנה סביבה, וממשקי Win32
# מקבלים wide. _A נשאר למרקר ולהשוואה מולו.
@"
// Generated by build_stub.ps1 from pubspec.yaml. Do not edit, do not commit.
#define PAYLOAD_VERSION_A "$version"
#define PAYLOAD_VERSION_W L"$version"
#define PAYLOAD_VERSION_COMMAS $commas
"@ | Set-Content -Path (Join-Path $outDir 'version.h') -Encoding utf8
Write-Host "Payload version: $version"

$vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
if (-not (Test-Path $vswhere)) {
  throw "vswhere.exe not found at $vswhere — Visual Studio with C++ tools is required."
}
$vsPath = & $vswhere -latest -products '*' `
  -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
  -property installationPath
if (-not $vsPath) { throw 'No Visual Studio installation with C++ tools was found.' }

$vcvars = Join-Path $vsPath 'VC\Auxiliary\Build\vcvars64.bat'
if (-not (Test-Path $vcvars)) { throw "vcvars64.bat not found at $vcvars." }

# דרך קובץ bat ולא `cmd /c "..."`: cmd מפרק מחרוזת עם מרכאות מקוננות
# בכללים משלו, וזה נשבר על נתיבים עם רווחים.
#
# /MT (CRT סטטי) הכרחי: ה-stub יושב מחוץ ל-app-files ולכן לא רואה את
# vcruntime140.dll שנוסע *בתוכה* (package.ps1 מעתיק אותו לשם; פלאטר לא).
# /utf-8 מאפשר את הטקסט העברי במקור ומונע C4819. אין כאן /WX בכוונה,
# בניגוד לרנר של Flutter: אזהרה בקובץ עזר של 70 שורות לא שווה CI אדום
# שבו הארטיפקט כולו לא נבנה.
$batPath = Join-Path $outDir '_build.bat'
@"
@echo off
call "$vcvars" >nul || exit /b 1
rc /nologo /i "$outDir" /fo "$outDir\stub.res" "$sourceDir\stub.rc" || exit /b 1
cl /nologo /utf-8 /W4 /O1 /MT /I"$outDir" /Fo"$outDir\stub.obj" /Fe"$outDir\stub.exe" ^
   "$sourceDir\stub.c" "$outDir\stub.res" ^
   /link /SUBSYSTEM:WINDOWS kernel32.lib user32.lib gdi32.lib cabinet.lib || exit /b 1
"@ | Set-Content -Path $batPath -Encoding oem

cmd /c $batPath
if ($LASTEXITCODE -ne 0) { throw "stub build failed with exit code $LASTEXITCODE." }
if (-not (Test-Path (Join-Path $outDir 'stub.exe'))) { throw 'stub.exe was not produced.' }

Write-Host "Built $outDir\stub.exe"
