# בונה את `חנות התוספים.exe` — קובץ אחד, בלי שום דבר לידו.
#
#   native\build.ps1              בנייה רגילה
#   native\build.ps1 -Run         בנייה והרצה
#   native\build.ps1 -Clean       מוחק את build\ ומתחיל מאפס
#
# דורש Visual Studio (או Build Tools) עם כלי C++. אין תלות ב-CMake:
# הבנייה היא קובץ מקור אחד לכל יחידה ולינק אחד, בדיוק כמו
# `windows_stub\build_stub.ps1` שהוכיח את עצמו בריפו הזה.
#
# ── למה ה-exe יוצא ~2-3MB ──────────────────────────────────────────────────────
#   • ה-loader של WebView2 מקושר **סטטית** → אין WebView2Loader.dll לידו
#   • ה-CRT מקושר סטטית (/MT) → אין vcruntime140.dll לידו
#   • קובצי הממשק דחוסים (LZMS) כ-resource → אין תיקיית ממשק לידו
#
# מנוע התצוגה עצמו הוא ה-WebView2 Runtime שכבר במחשב, ולכן הוא אינו
# נספר כאן. זה כל ההפרש מול 11.8MB של גרסת ה-Flutter, שנשאה איתה מנוע
# רינדור שלם.
param(
  [switch]$Run,
  [switch]$Clean,
  # בנייה עם סמלי ניפוי ובלי אופטימיזציה, לניפוי קריסות.
  [switch]$Debug
)
$ErrorActionPreference = 'Stop'

$nativeRoot = $PSScriptRoot
$srcDir = Join-Path $nativeRoot 'src'
$resDir = Join-Path $nativeRoot 'res'
$outDir = Join-Path $nativeRoot 'build'

# שם הקובץ שהמשתמש רואה — חייב להתאים ל-`OriginalFilename` שב-app.rc.
#
# ⚠️ **בלי "אוצריא" בשם**, בכוונה: הזיהוי של התקנת אוצריא עובד לפי השם,
# ו-exe בשם שמכיל "אוצריא" שיושב ב-`C:\אוצריא` היה נבחר שם כהתקנה של
# אוצריא עצמה. (הכלל הזה עבר כמו שהוא מגרסת ה-Flutter.)
$appFileName = 'חנות התוספים.exe'

if ($Clean -and (Test-Path $outDir)) { Remove-Item -Recurse -Force $outDir }
New-Item -ItemType Directory -Force $outDir | Out-Null

# תוצרי הביניים (obj, res, pdb) יורדים לתת-תיקייה, כדי ש-`build\` יראה
# בדיוק את מה שמפיצים: **קובץ אחד**. זה לא קוסמטי — ההבטחה של הפרויקט
# היא שאין שום דבר ליד ה-exe, וקל לאמת אותה בעין כשהתיקייה נקייה.
$objDir = Join-Path $outDir 'obj'
New-Item -ItemType Directory -Force $objDir | Out-Null

# ── 1. ה-SDK של WebView2 ─────────────────────────────────────────────────────
& (Join-Path $nativeRoot 'tools\fetch_webview2.ps1')

$sdkDir = Join-Path $nativeRoot 'third_party\Microsoft.Web.WebView2\build\native'
$sdkInclude = Join-Path $sdkDir 'include'
$sdkLib = Join-Path $sdkDir 'x64\WebView2LoaderStatic.lib'

# ── 2. משאב הגרסה ────────────────────────────────────────────────────────────
# הגרסה היא **מספר שלם אחד** (1, 2, 3…) — ראו tool/set_version.sh.
$versionFile = Join-Path $nativeRoot 'VERSION'
$version = (Get-Content -LiteralPath $versionFile -Raw).Trim()
if ($version -notmatch '^\d+$') {
  throw "native/VERSION must hold a single integer, found '$version'."
}

# אנגלית ו-ASCII בלבד: את הקובץ הזה קורא גם rc.exe, וקידוד של קובץ
# שמוכלל ב-.rc הוא בדיוק סוג התקלה שאין טעם להיכנס אליה בקובץ מיוצר.
#
# ⚠️ `ascii` ולא `utf8`, וזה **לא** אותו דבר כאן: ב-Windows PowerShell 5.1
# הערך `utf8` כותב BOM (‎EF BB BF), וב-pwsh 7 — שזה מה שה-CI מריץ — הוא
# כותב בלי. כלומר אותו סקריפט ייצר קובץ בשני קידודים שונים בין בנייה
# מקומית ל-CI, בקובץ שנכנס גם ל-rc.exe וגם ל-cl.exe. התוכן כאן הוא
# ספרות ו-`#define`, ולכן `ascii` הוא בדיוק מה שההערה שמעל מבטיחה.
@"
// Generated by native/build.ps1 from native/VERSION. Do not edit, do not commit.
#define APP_VERSION_A "$version"
#define APP_VERSION_W L"$version"
#define APP_VERSION_COMMAS $version,0,0,0
"@ | Set-Content -LiteralPath (Join-Path $outDir 'version.h') -Encoding ascii
Write-Host "Version: $version"

# ── 3. חבילת הממשק ───────────────────────────────────────────────────────────
& (Join-Path $nativeRoot 'tools\pack_web.ps1')

# rc.exe מחפש קובצי משאב גם בנתיבי ה-include, ולכן res\ ו-build\ נמסרים
# לו כ-/i. ה-manifest יושב ליד ה-rc עצמו.
$iconPath = Join-Path $resDir 'app_icon.ico'
if (-not (Test-Path -LiteralPath $iconPath)) {
  throw "Missing $iconPath — build the icon with tool\make_app_icon.ps1."
}

# ── 4. איתור הקומפיילר ───────────────────────────────────────────────────────
$vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
if (-not (Test-Path $vswhere)) {
  throw "vswhere.exe not found at $vswhere — Visual Studio with C++ tools is required."
}
$vsPath = & $vswhere -latest -products '*' `
  -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
  -property installationPath
if (-not $vsPath) { throw 'No Visual Studio installation with C++ tools was found.' }

$vcvars = Join-Path $vsPath 'VC\Auxiliary\Build\vcvars64.bat'
if (-not (Test-Path $vcvars)) { throw "vcvars64.bat not found at $vcvars." }

# ── 5. קומפילציה ולינק ───────────────────────────────────────────────────────
$sources = @(
  'main.cpp', 'bridge.cpp', 'common.cpp', 'fsapi.cpp', 'netapi.cpp',
  'overlay.cpp', 'paths.cpp', 'sysapi.cpp', 'webres.cpp'
) | ForEach-Object { '"' + (Join-Path $srcDir $_) + '"' }

# /MT — CRT סטטי, וזו החלטה מרכזית: בלעדיו ה-exe דורש
# `vcruntime140.dll` לידו, וכל הרעיון כאן הוא קובץ אחד. (בגרסת
# ה-Flutter היו שלושה DLL של ה-CRT בתוך ה-payload בדיוק בשביל זה.)
#
# /O1 — אופטימיזציה **לגודל**, לא למהירות. כל העבודה הכבדה כאן היא I/O
# ורשת; אין כאן לולאה חמה שתרוויח מ-/O2.
#
# /utf-8 — המקור מכיל עברית (הודעות שגיאה). בלעדיו C4819 ותווים שבורים.
$commonFlags = '/nologo /std:c++17 /EHsc /W4 /utf-8 /DUNICODE /D_UNICODE /DWIN32_LEAN_AND_MEAN'
if ($Debug) {
  $compileFlags = "$commonFlags /Od /MTd /Zi /D_DEBUG"
  $linkExtra = '/DEBUG'
} else {
  $compileFlags = "$commonFlags /O1 /MT /GS /DNDEBUG"
  # /OPT:REF ו-/OPT:ICF זורקים קוד ונתונים שלא בשימוש ומאחדים כפילויות
  # — הם לבדם מורידים כמה מאות KB מהלינק עם ה-loader הסטטי.
  $linkExtra = '/OPT:REF /OPT:ICF'
}

# comctl32 — ה-progress bar של חלון פריסת החבילה (overlay.cpp). הוא
# משאיר את ה-exe בגודלו: ה-DLL כבר טעון בכל תהליך שיש לו חלון.
$libs = @(
  'version.lib', 'shlwapi.lib', 'dwmapi.lib', 'winhttp.lib', 'cabinet.lib',
  'crypt32.lib', 'ole32.lib', 'oleaut32.lib', 'shell32.lib', 'user32.lib',
  'gdi32.lib', 'advapi32.lib', 'kernel32.lib', 'comdlg32.lib', 'uuid.lib',
  'comctl32.lib'
) -join ' '

$exePath = Join-Path $outDir $appFileName

# ⚠️ הלינק יוצר קובץ בשם **אנגלי**, וההעברה לשם העברי נעשית ב-PowerShell
# אחר כך.
#
# למה: קובץ ה-bat נשמר בקוד-עמוד OEM (זה מה ש-cmd קורא), והשם העברי
# נהרס בהמרה — הלינקר יצר קובץ בשם ג'יבריש, והבנייה "נכשלה" בעוד שה-exe
# היה שם כל הזמן תחת שם אחר. אין שום נתיב עברי בתוך ה-bat.
$linkName = 'otzaria-plugin-store.exe'
$linkPath = Join-Path $outDir $linkName

# דרך קובץ bat ולא `cmd /c "..."`: cmd מפרק מחרוזת עם מרכאות מקוננות
# בכללים משלו, וזה נשבר על נתיבים עם רווחים.
$batPath = Join-Path $outDir '_build.bat'

# ⚠️ הקובץ נכתב **UTF-8 בלי BOM**, ו-`chcp 65001` בשורה השנייה אומר
# ל-cmd לקרוא כך את השורות שאחריה.
#
# למה: קודם הוא נכתב ב-`oem`, ואז כל תו בנתיב שקוד-העמוד של המערכת
# אינו יודע לייצג הפך ל-`?` בשקט. הנתיבים כאן נגזרים מ-$PSScriptRoot,
# כלומר ממקום ה-checkout — וריפו עברי כמו זה נשמר לא פעם תחת נתיב עברי
# (למשל בתוך תיקיית משתמש עברית). על מערכת עם OEM 437 זה ייצר bat עם
# נתיבים שבורים, וההודעה שהמשתמש רואה היא "cannot open source file" —
# שאינה מרמזת ולו במעט על קידוד.
#
# שתי השורות הראשונות הן ASCII טהור ולכן נקראות נכון בכל קוד-עמוד, וזה
# כל מה שנדרש כדי ש-`chcp` יספיק לפעול לפני השורות עם הנתיבים.
#
# **בלי BOM**: cmd היה מריץ אותו כתווים בשורה הראשונה ומדפיס שגיאה.
# `Set-Content -Encoding utf8` כותב BOM ב-5.1, ולכן הכתיבה כאן ישירה.
$batText = @"
@echo off
chcp 65001 >nul
call "$vcvars" >nul || exit /b 1
cd /d "$outDir" || exit /b 1
rc /nologo /i "$resDir" /i "$outDir" /i "$srcDir" /fo "$objDir\app.res" "$srcDir\app.rc" || exit /b 1
cl $compileFlags /I"$sdkInclude" /I"$srcDir" /I"$outDir" ^
   $($sources -join ' ') ^
   /Fo"$objDir\\" /Fd"$objDir\\" /Fe"$linkPath" ^
   /link /SUBSYSTEM:WINDOWS $linkExtra "$sdkLib" "$objDir\app.res" $libs || exit /b 1
"@
# CRLF במפורש: cmd מתמודד רע עם bat שכולו LF, ו-here-string יורש את
# סופי השורה של הקובץ הזה — שאינם מובטחים אחרי checkout.
$batText = ($batText -replace "`r`n", "`n") -replace "`n", "`r`n"
[IO.File]::WriteAllText($batPath, $batText + "`r`n",
  (New-Object Text.UTF8Encoding($false)))

cmd /c $batPath
if ($LASTEXITCODE -ne 0) { throw "build failed with exit code $LASTEXITCODE." }
if (-not (Test-Path -LiteralPath $linkPath)) { throw "the exe was not produced ($linkPath)." }

# השם שהמשתמש רואה מוצב כאן, מחוץ ל-bat.
if (Test-Path -LiteralPath $exePath) { Remove-Item -LiteralPath $exePath -Force }
Move-Item -LiteralPath $linkPath -Destination $exePath -Force

$sizeMb = [math]::Round((Get-Item -LiteralPath $exePath).Length / 1MB, 2)
Write-Host ''
Write-Host "Built $exePath ($sizeMb MB)" -ForegroundColor Green

# מאמת את ההבטחה המרכזית של הפרויקט: קובץ אחד, בלי DLL לידו.
$strays = Get-ChildItem -LiteralPath $outDir -Filter '*.dll' -ErrorAction SilentlyContinue
if ($strays) {
  Write-Warning "Unexpected DLLs next to the exe: $($strays.Name -join ', ')"
}

if ($Run) {
  Write-Host "Running $appFileName …"
  Start-Process -FilePath $exePath
}
